// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYnnpbwcFvkhyQIdfhEgyxXB-5TmjoR2E',
    appId: '1:163555474751:web:97eca33b9dc9e1c876a78a',
    messagingSenderId: '163555474751',
    projectId: 'qrcodevio',
    authDomain: 'qrcodevio.firebaseapp.com',
    storageBucket: 'qrcodevio.appspot.com',
    measurementId: 'G-S4B66WTJ80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgzmqmt20nrJx7qGSs9bSjrCum4wVXxmk',
    appId: '1:163555474751:android:38005ef3171d362776a78a',
    messagingSenderId: '163555474751',
    projectId: 'qrcodevio',
    storageBucket: 'qrcodevio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcl1vrtsR_DMdPezovyfFsIVI34R8435U',
    appId: '1:163555474751:ios:aecd0fb76bd5955876a78a',
    messagingSenderId: '163555474751',
    projectId: 'qrcodevio',
    storageBucket: 'qrcodevio.appspot.com',
    iosClientId: '163555474751-1vcf4rh74f0e27uecljgs3c45s2hkj7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcl1vrtsR_DMdPezovyfFsIVI34R8435U',
    appId: '1:163555474751:ios:91184a396e05996476a78a',
    messagingSenderId: '163555474751',
    projectId: 'qrcodevio',
    storageBucket: 'qrcodevio.appspot.com',
    iosClientId: '163555474751-jtk080uo17sd5sjieebfgoi0erv6bf6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode.RunnerTests',
  );
}
